### PR TITLE
Add to db

### PR DESCRIPTION
**Pull request by mboneil10**
So I added some data to the database. I don't know if it makes sense. But here it is.

### CODE REVIEW

**Comment by mboneil10** [comment]
It doesn't work with the markdown currently in place, but I think that should be fine after @Cobchise finishes the markdown schtuff and merges.

**Comment by L4r1k** [comment]
I downloaded this branch but it doesn't seem to add anything to the database 😕

**Comment by L4r1k** [comment]
Also scared to merge it because I think it might overwrite what's in there now

**Comment by mboneil10** [comment]
Damnit. I'll just close it.

**Pull request closed without merging**
